### ISSUE TITLE
Error when using multiple lines on an hologram

### ISSUE THREAD

**Issue by kill05** [TheLimeGlass/Graphisk#1]
On load, I get this error since i've tried to use multiple lines on an hologram. Also it returns an error an error with an ArrayList and with a class of holographicdisplays, so I assumed I should report to you. Thanks.

> [18:10:43 ERROR]: #!#!
> [18:10:43 ERROR]: #!#! [Skript] Severe Error:
> [18:10:43 ERROR]: #!#!
> [18:10:43 ERROR]: #!#! Something went horribly wrong with Skript.
> [18:10:43 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [18:10:43 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
> [18:10:43 ERROR]: #!#! Here is full list of them:
> [18:10:43 ERROR]: #!#! SkBee v1.10.1 (https://github.com/ShaneBeee/SkBee) HolographicDisplaysAddon v1.0.0b Factions v1.6.9.5-2.2.9-RC SkUniversal v2.11.5
> [18:10:43 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
> [18:10:43 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
> [18:10:43 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
> [18:10:43 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
> [18:10:43 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
> [18:10:43 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
> [18:10:43 ERROR]: #!#!
> [18:10:43 ERROR]: #!#! Stack trace:
> [18:10:43 ERROR]: #!#! java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
> [18:10:43 ERROR]: #!#! at java.util.ArrayList.rangeCheck(ArrayList.java:659)
> [18:10:43 ERROR]: #!#! at java.util.ArrayList.get(ArrayList.java:435)
> [18:10:43 ERROR]: #!#! at com.gmail.filoghost.holographicdisplays.object.CraftHologram.getLine(CraftHologram.java:121)
> [18:10:43 ERROR]: #!#! at com.gmail.filoghost.holographicdisplays.object.CraftHologram.getLine(CraftHologram.java:37)
> [18:10:43 ERROR]: #!#! at me.limeglass.hda.elements.effects.EffSetTextLine.execute(EffSetTextLine.java:21)
> [18:10:43 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:51)
> [18:10:43 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
> [18:10:43 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
> [18:10:43 ERROR]: #!#! at ch.njol.skript.effects.Delay$1.run(Delay.java:108)
> [18:10:43 ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
> [18:10:43 ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
> [18:10:43 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
> [18:10:43 ERROR]: #!#! at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> [18:10:43 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
> [18:10:43 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
> [18:10:43 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
> [18:10:43 ERROR]: #!#!
> [18:10:43 ERROR]: #!#! Version Information:
> [18:10:43 ERROR]: #!#! Skript: 2.5.3 (latest)
> [18:10:43 ERROR]: #!#! Flavor: github-matocolotoe-1.8
> [18:10:43 ERROR]: #!#! Date: 2020-12-22
> [18:10:43 ERROR]: #!#! Bukkit: 1.8.8-R0.1-SNAPSHOT
> [18:10:43 ERROR]: #!#! Minecraft: 1.8.8
> [18:10:43 ERROR]: #!#! Java: 1.8.0_275 (OpenJDK 64-Bit Server VM 25.275-b01)
> [18:10:43 ERROR]: #!#! OS: Linux amd64 5.4.0-62-generic
> [18:10:43 ERROR]: #!#!
> [18:10:43 ERROR]: #!#! Server platform: Paper
> [18:10:43 ERROR]: #!#!
> [18:10:43 ERROR]: #!#! Current node: null
> [18:10:43 ERROR]: #!#! Current item: [HolographicAddon] EffSetTextLine- Syntax: [Ljava.lang.String;@25a29c7b
> [18:10:43 ERROR]: #!#! Current trigger: skript start (on server start) (machines.sk, line 25)
> [18:10:43 ERROR]: #!#!
> [18:10:43 ERROR]: #!#! Thread: Server thread
> [18:10:43 ERROR]: #!#!
> [18:10:43 ERROR]: #!#! Language: english
> [18:10:43 ERROR]: #!#! Link parse mode: DISABLED
> [18:10:43 ERROR]: #!#!
> [18:10:43 ERROR]: #!#! End of Error.
> [18:10:43 ERROR]: #!#!

**Comment by TheLimeGlass** [comment]
Please provide your Skript coding, you're telling holographic displays to set a line which has not been added to the hologram yet.

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.0
